name: Build Windows EXE

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build EXE
        run: |
          pyinstaller app.py --onefile --noconsole --clean --strip --name jimmy_app

      - name: Upload EXE artifact
        uses: actions/upload-artifact@v2
        with:
          name: jimmy_app_exe
          path: dist/jimmy_app.exe 