name: Build Windows EXE

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.2.2

      - name: Set up Python
        uses: actions/setup-python@v4 # Pinned by SHA in logs - 7f4fc3e22c37d6ff65e88745f38bd3157c663f7c
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build EXE
        run: |
          pyinstaller app.py --onefile --noconsole --clean --strip --name jimmy_app

      - name: Upload EXE artifact
        uses: actions/upload-artifact@ea165f8 # v4.6.2
        with:
          name: jimmy_app_exe
          path: dist/jimmy_app.exe 